FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["SwipeVibesAPI.csproj", "./"]
RUN dotnet restore "SwipeVibesAPI.csproj"

COPY . .
RUN dotnet publish "SwipeVibesAPI.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "SwipeVibesAPI.dll"]