// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file deezer.proto (package deezer, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum deezer.ExplicitLevel
 */
export enum ExplicitLevel {
  /**
   * @generated from enum value: EXPLICIT_LEVEL_UNSPECIFIED = 0;
   */
  EXPLICIT_LEVEL_UNSPECIFIED = 0,

  /**
   * @generated from enum value: CLEAN = 1;
   */
  CLEAN = 1,

  /**
   * @generated from enum value: EXPLICIT = 2;
   */
  EXPLICIT = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(ExplicitLevel)
proto3.util.setEnumType(ExplicitLevel, "deezer.ExplicitLevel", [
  { no: 0, name: "EXPLICIT_LEVEL_UNSPECIFIED" },
  { no: 1, name: "CLEAN" },
  { no: 2, name: "EXPLICIT" },
]);

/**
 * @generated from message deezer.Artist
 */
export class Artist extends Message<Artist> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: string link = 3;
   */
  link = "";

  /**
   * @generated from field: string picture = 4;
   */
  picture = "";

  /**
   * @generated from field: string picture_small = 5;
   */
  pictureSmall = "";

  /**
   * @generated from field: string picture_medium = 6;
   */
  pictureMedium = "";

  /**
   * @generated from field: string picture_big = 7;
   */
  pictureBig = "";

  /**
   * @generated from field: string picture_xl = 8;
   */
  pictureXl = "";

  /**
   * @generated from field: string tracklist = 9;
   */
  tracklist = "";

  constructor(data?: PartialMessage<Artist>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "deezer.Artist";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "link", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "picture", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "picture_small", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "picture_medium", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "picture_big", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "picture_xl", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "tracklist", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Artist {
    return new Artist().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Artist {
    return new Artist().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Artist {
    return new Artist().fromJsonString(jsonString, options);
  }

  static equals(a: Artist | PlainMessage<Artist> | undefined, b: Artist | PlainMessage<Artist> | undefined): boolean {
    return proto3.util.equals(Artist, a, b);
  }
}

/**
 * @generated from message deezer.Album
 */
export class Album extends Message<Album> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * @generated from field: string cover = 3;
   */
  cover = "";

  /**
   * @generated from field: string cover_small = 4;
   */
  coverSmall = "";

  /**
   * @generated from field: string cover_medium = 5;
   */
  coverMedium = "";

  /**
   * @generated from field: string cover_big = 6;
   */
  coverBig = "";

  /**
   * @generated from field: string cover_xl = 7;
   */
  coverXl = "";

  /**
   * @generated from field: string tracklist = 8;
   */
  tracklist = "";

  constructor(data?: PartialMessage<Album>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "deezer.Album";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "cover", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "cover_small", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "cover_medium", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "cover_big", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "cover_xl", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "tracklist", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Album {
    return new Album().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Album {
    return new Album().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Album {
    return new Album().fromJsonString(jsonString, options);
  }

  static equals(a: Album | PlainMessage<Album> | undefined, b: Album | PlainMessage<Album> | undefined): boolean {
    return proto3.util.equals(Album, a, b);
  }
}

/**
 * @generated from message deezer.Track
 */
export class Track extends Message<Track> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  /**
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * @generated from field: string title_short = 3;
   */
  titleShort = "";

  /**
   * @generated from field: string isrc = 4;
   */
  isrc = "";

  /**
   * @generated from field: string link = 5;
   */
  link = "";

  /**
   * @generated from field: string share = 6;
   */
  share = "";

  /**
   * @generated from field: int32 track_position = 7;
   */
  trackPosition = 0;

  /**
   * @generated from field: int32 disk_number = 8;
   */
  diskNumber = 0;

  /**
   * @generated from field: int32 rank = 9;
   */
  rank = 0;

  /**
   * @generated from field: google.protobuf.Timestamp release_date = 10;
   */
  releaseDate?: Timestamp;

  /**
   * @generated from field: bool explicit_lyrics = 11;
   */
  explicitLyrics = false;

  /**
   * @generated from field: deezer.ExplicitLevel explicit_content_lyrics = 12;
   */
  explicitContentLyrics = ExplicitLevel.EXPLICIT_LEVEL_UNSPECIFIED;

  /**
   * @generated from field: deezer.ExplicitLevel explicit_cover = 13;
   */
  explicitCover = ExplicitLevel.EXPLICIT_LEVEL_UNSPECIFIED;

  /**
   * @generated from field: string preview = 14;
   */
  preview = "";

  /**
   * @generated from field: double bpm = 15;
   */
  bpm = 0;

  /**
   * @generated from field: double gain = 16;
   */
  gain = 0;

  /**
   * @generated from field: repeated string country_codes = 17;
   */
  countryCodes: string[] = [];

  /**
   * @generated from field: repeated deezer.Artist artists = 18;
   */
  artists: Artist[] = [];

  /**
   * @generated from field: deezer.Album album = 19;
   */
  album?: Album;

  constructor(data?: PartialMessage<Track>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "deezer.Track";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "title_short", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "isrc", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "link", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "share", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "track_position", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "disk_number", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "rank", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "release_date", kind: "message", T: Timestamp },
    { no: 11, name: "explicit_lyrics", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 12, name: "explicit_content_lyrics", kind: "enum", T: proto3.getEnumType(ExplicitLevel) },
    { no: 13, name: "explicit_cover", kind: "enum", T: proto3.getEnumType(ExplicitLevel) },
    { no: 14, name: "preview", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 15, name: "bpm", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 16, name: "gain", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 17, name: "country_codes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 18, name: "artists", kind: "message", T: Artist, repeated: true },
    { no: 19, name: "album", kind: "message", T: Album },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Track {
    return new Track().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Track {
    return new Track().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Track {
    return new Track().fromJsonString(jsonString, options);
  }

  static equals(a: Track | PlainMessage<Track> | undefined, b: Track | PlainMessage<Track> | undefined): boolean {
    return proto3.util.equals(Track, a, b);
  }
}

/**
 * @generated from message deezer.GetTrackRequest
 */
export class GetTrackRequest extends Message<GetTrackRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id = protoInt64.zero;

  constructor(data?: PartialMessage<GetTrackRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "deezer.GetTrackRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTrackRequest {
    return new GetTrackRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTrackRequest {
    return new GetTrackRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTrackRequest {
    return new GetTrackRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetTrackRequest | PlainMessage<GetTrackRequest> | undefined, b: GetTrackRequest | PlainMessage<GetTrackRequest> | undefined): boolean {
    return proto3.util.equals(GetTrackRequest, a, b);
  }
}

/**
 * @generated from message deezer.GetTrackResponse
 */
export class GetTrackResponse extends Message<GetTrackResponse> {
  /**
   * @generated from field: deezer.Track track = 1;
   */
  track?: Track;

  constructor(data?: PartialMessage<GetTrackResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "deezer.GetTrackResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "track", kind: "message", T: Track },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTrackResponse {
    return new GetTrackResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTrackResponse {
    return new GetTrackResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTrackResponse {
    return new GetTrackResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetTrackResponse | PlainMessage<GetTrackResponse> | undefined, b: GetTrackResponse | PlainMessage<GetTrackResponse> | undefined): boolean {
    return proto3.util.equals(GetTrackResponse, a, b);
  }
}

