// @generated by protoc-gen-connect-web v0.8.6 with parameter "target=ts,import_extension=none"
// @generated from file deezer.proto (package deezer, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTrackRequest, GetTrackResponse } from "./deezer_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service deezer.DeezerService
 */
export const DeezerService = {
  typeName: "deezer.DeezerService",
  methods: {
    /**
     * @generated from rpc deezer.DeezerService.GetTrack
     */
    getTrack: {
      name: "GetTrack",
      I: GetTrackRequest,
      O: GetTrackResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

