// @generated by protoc-gen-connect-web v0.8.6 with parameter "target=ts,import_extension=none"
// @generated from file gemini.proto (package gemini, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetGeminiTrackRecommendationRequest, GetGeminiTrackRecommendationResponse } from "./gemini_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service gemini.GeminiService
 */
export const GeminiService = {
  typeName: "gemini.GeminiService",
  methods: {
    /**
     * @generated from rpc gemini.GeminiService.GetGeminiTrackRecommendation
     */
    getGeminiTrackRecommendation: {
      name: "GetGeminiTrackRecommendation",
      I: GetGeminiTrackRecommendationRequest,
      O: GetGeminiTrackRecommendationResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

