// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file gemini.proto (package gemini, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { InteractionReply } from "./users_pb.js";

/**
 * @generated from message gemini.GetGeminiTrackRecommendationRequest
 */
export class GetGeminiTrackRecommendationRequest extends Message<GetGeminiTrackRecommendationRequest> {
  /**
   * @generated from field: string prompt = 1;
   */
  prompt = "";

  /**
   * @generated from field: repeated users.InteractionReply interactions = 2;
   */
  interactions: InteractionReply[] = [];

  /**
   * @generated from field: repeated string genre_filters = 3;
   */
  genreFilters: string[] = [];

  /**
   * @generated from field: repeated string language_filters = 4;
   */
  languageFilters: string[] = [];

  constructor(data?: PartialMessage<GetGeminiTrackRecommendationRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "gemini.GetGeminiTrackRecommendationRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "prompt", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "interactions", kind: "message", T: InteractionReply, repeated: true },
    { no: 3, name: "genre_filters", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "language_filters", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetGeminiTrackRecommendationRequest {
    return new GetGeminiTrackRecommendationRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetGeminiTrackRecommendationRequest {
    return new GetGeminiTrackRecommendationRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetGeminiTrackRecommendationRequest {
    return new GetGeminiTrackRecommendationRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetGeminiTrackRecommendationRequest | PlainMessage<GetGeminiTrackRecommendationRequest> | undefined, b: GetGeminiTrackRecommendationRequest | PlainMessage<GetGeminiTrackRecommendationRequest> | undefined): boolean {
    return proto3.util.equals(GetGeminiTrackRecommendationRequest, a, b);
  }
}

/**
 * @generated from message gemini.GetGeminiTrackRecommendationResponse
 */
export class GetGeminiTrackRecommendationResponse extends Message<GetGeminiTrackRecommendationResponse> {
  /**
   * @generated from field: repeated string recommended_artist_names = 1;
   */
  recommendedArtistNames: string[] = [];

  constructor(data?: PartialMessage<GetGeminiTrackRecommendationResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "gemini.GetGeminiTrackRecommendationResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "recommended_artist_names", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetGeminiTrackRecommendationResponse {
    return new GetGeminiTrackRecommendationResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetGeminiTrackRecommendationResponse {
    return new GetGeminiTrackRecommendationResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetGeminiTrackRecommendationResponse {
    return new GetGeminiTrackRecommendationResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetGeminiTrackRecommendationResponse | PlainMessage<GetGeminiTrackRecommendationResponse> | undefined, b: GetGeminiTrackRecommendationResponse | PlainMessage<GetGeminiTrackRecommendationResponse> | undefined): boolean {
    return proto3.util.equals(GetGeminiTrackRecommendationResponse, a, b);
  }
}

