// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file interactions.proto (package swipevibes, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message swipevibes.LogRequest
 */
export class LogRequest extends Message<LogRequest> {
  /**
   * @generated from field: string isrc = 1;
   */
  isrc = "";

  /**
   * like|dislike|skip|impression
   *
   * @generated from field: string decision = 2;
   */
  decision = "";

  /**
   * @generated from field: int64 deezer_track_id = 3;
   */
  deezerTrackId = protoInt64.zero;

  /**
   * @generated from field: string source = 4;
   */
  source = "";

  /**
   * @generated from field: string preview_url = 5;
   */
  previewUrl = "";

  /**
   * @generated from field: string artist = 6;
   */
  artist = "";

  /**
   * @generated from field: string title = 7;
   */
  title = "";

  /**
   * @generated from field: string album = 8;
   */
  album = "";

  /**
   * @generated from field: double bpm = 9;
   */
  bpm = 0;

  /**
   * @generated from field: double gain = 10;
   */
  gain = 0;

  /**
   * Position in recommendation queue (1-indexed)
   *
   * @generated from field: int32 position = 11;
   */
  position = 0;

  constructor(data?: PartialMessage<LogRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "swipevibes.LogRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "isrc", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "decision", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "deezer_track_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "preview_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "artist", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "album", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "bpm", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 10, name: "gain", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 11, name: "position", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LogRequest {
    return new LogRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LogRequest {
    return new LogRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LogRequest {
    return new LogRequest().fromJsonString(jsonString, options);
  }

  static equals(a: LogRequest | PlainMessage<LogRequest> | undefined, b: LogRequest | PlainMessage<LogRequest> | undefined): boolean {
    return proto3.util.equals(LogRequest, a, b);
  }
}

/**
 * @generated from message swipevibes.LogReply
 */
export class LogReply extends Message<LogReply> {
  /**
   * @generated from field: bool ok = 1;
   */
  ok = false;

  /**
   * @generated from field: string id = 2;
   */
  id = "";

  constructor(data?: PartialMessage<LogReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "swipevibes.LogReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "ok", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LogReply {
    return new LogReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LogReply {
    return new LogReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LogReply {
    return new LogReply().fromJsonString(jsonString, options);
  }

  static equals(a: LogReply | PlainMessage<LogReply> | undefined, b: LogReply | PlainMessage<LogReply> | undefined): boolean {
    return proto3.util.equals(LogReply, a, b);
  }
}

