// @generated by protoc-gen-connect-web v0.8.6 with parameter "target=ts,import_extension=none"
// @generated from file interactions.proto (package swipevibes, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { LogReply, LogRequest } from "./interactions_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service swipevibes.InteractionService
 */
export const InteractionService = {
  typeName: "swipevibes.InteractionService",
  methods: {
    /**
     * @generated from rpc swipevibes.InteractionService.Log
     */
    log: {
      name: "Log",
      I: LogRequest,
      O: LogReply,
      kind: MethodKind.Unary,
    },
  }
} as const;

