// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file users.proto (package users, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message users.RefreshRequest
 */
export class RefreshRequest extends Message<RefreshRequest> {
  /**
   * for native; for web this will be cookie
   *
   * @generated from field: string refresh_token = 1;
   */
  refreshToken = "";

  constructor(data?: PartialMessage<RefreshRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.RefreshRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshRequest {
    return new RefreshRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshRequest {
    return new RefreshRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshRequest {
    return new RefreshRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RefreshRequest | PlainMessage<RefreshRequest> | undefined, b: RefreshRequest | PlainMessage<RefreshRequest> | undefined): boolean {
    return proto3.util.equals(RefreshRequest, a, b);
  }
}

/**
 * @generated from message users.RefreshReply
 */
export class RefreshReply extends Message<RefreshReply> {
  /**
   * @generated from field: string token = 1;
   */
  token = "";

  constructor(data?: PartialMessage<RefreshReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.RefreshReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshReply {
    return new RefreshReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshReply {
    return new RefreshReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshReply {
    return new RefreshReply().fromJsonString(jsonString, options);
  }

  static equals(a: RefreshReply | PlainMessage<RefreshReply> | undefined, b: RefreshReply | PlainMessage<RefreshReply> | undefined): boolean {
    return proto3.util.equals(RefreshReply, a, b);
  }
}

/**
 * @generated from message users.LogoutRequest
 */
export class LogoutRequest extends Message<LogoutRequest> {
  constructor(data?: PartialMessage<LogoutRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.LogoutRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LogoutRequest {
    return new LogoutRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LogoutRequest {
    return new LogoutRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LogoutRequest {
    return new LogoutRequest().fromJsonString(jsonString, options);
  }

  static equals(a: LogoutRequest | PlainMessage<LogoutRequest> | undefined, b: LogoutRequest | PlainMessage<LogoutRequest> | undefined): boolean {
    return proto3.util.equals(LogoutRequest, a, b);
  }
}

/**
 * @generated from message users.LogoutReply
 */
export class LogoutReply extends Message<LogoutReply> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  constructor(data?: PartialMessage<LogoutReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.LogoutReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LogoutReply {
    return new LogoutReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LogoutReply {
    return new LogoutReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LogoutReply {
    return new LogoutReply().fromJsonString(jsonString, options);
  }

  static equals(a: LogoutReply | PlainMessage<LogoutReply> | undefined, b: LogoutReply | PlainMessage<LogoutReply> | undefined): boolean {
    return proto3.util.equals(LogoutReply, a, b);
  }
}

/**
 * @generated from message users.Empty
 */
export class Empty extends Message<Empty> {
  constructor(data?: PartialMessage<Empty>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.Empty";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Empty {
    return new Empty().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Empty {
    return new Empty().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Empty {
    return new Empty().fromJsonString(jsonString, options);
  }

  static equals(a: Empty | PlainMessage<Empty> | undefined, b: Empty | PlainMessage<Empty> | undefined): boolean {
    return proto3.util.equals(Empty, a, b);
  }
}

/**
 * @generated from message users.UserRequest
 */
export class UserRequest extends Message<UserRequest> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  constructor(data?: PartialMessage<UserRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.UserRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserRequest {
    return new UserRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserRequest {
    return new UserRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserRequest {
    return new UserRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UserRequest | PlainMessage<UserRequest> | undefined, b: UserRequest | PlainMessage<UserRequest> | undefined): boolean {
    return proto3.util.equals(UserRequest, a, b);
  }
}

/**
 * @generated from message users.CreateUserRequest
 */
export class CreateUserRequest extends Message<CreateUserRequest> {
  /**
   * @generated from field: string username = 1;
   */
  username = "";

  /**
   * @generated from field: string email = 2;
   */
  email = "";

  /**
   * @generated from field: string password = 3;
   */
  password = "";

  constructor(data?: PartialMessage<CreateUserRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.CreateUserRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateUserRequest {
    return new CreateUserRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateUserRequest {
    return new CreateUserRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateUserRequest {
    return new CreateUserRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateUserRequest | PlainMessage<CreateUserRequest> | undefined, b: CreateUserRequest | PlainMessage<CreateUserRequest> | undefined): boolean {
    return proto3.util.equals(CreateUserRequest, a, b);
  }
}

/**
 * @generated from message users.UpdateUserRequest
 */
export class UpdateUserRequest extends Message<UpdateUserRequest> {
  /**
   * @generated from field: int32 id = 1;
   */
  id = 0;

  /**
   * @generated from field: string username = 2;
   */
  username = "";

  /**
   * @generated from field: string email = 3;
   */
  email = "";

  /**
   * @generated from field: string password = 4;
   */
  password = "";

  constructor(data?: PartialMessage<UpdateUserRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.UpdateUserRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateUserRequest {
    return new UpdateUserRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateUserRequest {
    return new UpdateUserRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateUserRequest {
    return new UpdateUserRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UpdateUserRequest | PlainMessage<UpdateUserRequest> | undefined, b: UpdateUserRequest | PlainMessage<UpdateUserRequest> | undefined): boolean {
    return proto3.util.equals(UpdateUserRequest, a, b);
  }
}

/**
 * @generated from message users.LoginRequest
 */
export class LoginRequest extends Message<LoginRequest> {
  /**
   * @generated from field: string username = 1;
   */
  username = "";

  /**
   * @generated from field: string password = 2;
   */
  password = "";

  /**
   * @generated from field: string provider = 3;
   */
  provider = "";

  /**
   * @generated from field: string token = 4;
   */
  token = "";

  constructor(data?: PartialMessage<LoginRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.LoginRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "provider", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LoginRequest {
    return new LoginRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LoginRequest {
    return new LoginRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LoginRequest {
    return new LoginRequest().fromJsonString(jsonString, options);
  }

  static equals(a: LoginRequest | PlainMessage<LoginRequest> | undefined, b: LoginRequest | PlainMessage<LoginRequest> | undefined): boolean {
    return proto3.util.equals(LoginRequest, a, b);
  }
}

/**
 * @generated from message users.UserReply
 */
export class UserReply extends Message<UserReply> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string username = 2;
   */
  username = "";

  /**
   * @generated from field: string email = 3;
   */
  email = "";

  /**
   * @generated from field: string role = 4;
   */
  role = "";

  constructor(data?: PartialMessage<UserReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.UserReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "role", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserReply {
    return new UserReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserReply {
    return new UserReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserReply {
    return new UserReply().fromJsonString(jsonString, options);
  }

  static equals(a: UserReply | PlainMessage<UserReply> | undefined, b: UserReply | PlainMessage<UserReply> | undefined): boolean {
    return proto3.util.equals(UserReply, a, b);
  }
}

/**
 * @generated from message users.UsersReply
 */
export class UsersReply extends Message<UsersReply> {
  /**
   * @generated from field: repeated users.UserReply users = 1;
   */
  users: UserReply[] = [];

  constructor(data?: PartialMessage<UsersReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.UsersReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "users", kind: "message", T: UserReply, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UsersReply {
    return new UsersReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UsersReply {
    return new UsersReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UsersReply {
    return new UsersReply().fromJsonString(jsonString, options);
  }

  static equals(a: UsersReply | PlainMessage<UsersReply> | undefined, b: UsersReply | PlainMessage<UsersReply> | undefined): boolean {
    return proto3.util.equals(UsersReply, a, b);
  }
}

/**
 * @generated from message users.DeleteReply
 */
export class DeleteReply extends Message<DeleteReply> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  constructor(data?: PartialMessage<DeleteReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.DeleteReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteReply {
    return new DeleteReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteReply {
    return new DeleteReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteReply {
    return new DeleteReply().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteReply | PlainMessage<DeleteReply> | undefined, b: DeleteReply | PlainMessage<DeleteReply> | undefined): boolean {
    return proto3.util.equals(DeleteReply, a, b);
  }
}

/**
 * @generated from message users.LoginReply
 */
export class LoginReply extends Message<LoginReply> {
  /**
   * @generated from field: string token = 1;
   */
  token = "";

  /**
   * @generated from field: string username = 2;
   */
  username = "";

  /**
   * @generated from field: string role = 3;
   */
  role = "";

  /**
   * @generated from field: string refresh_token = 4;
   */
  refreshToken = "";

  constructor(data?: PartialMessage<LoginReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.LoginReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "role", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LoginReply {
    return new LoginReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LoginReply {
    return new LoginReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LoginReply {
    return new LoginReply().fromJsonString(jsonString, options);
  }

  static equals(a: LoginReply | PlainMessage<LoginReply> | undefined, b: LoginReply | PlainMessage<LoginReply> | undefined): boolean {
    return proto3.util.equals(LoginReply, a, b);
  }
}

/**
 * @generated from message users.UserInteractionsRequest
 */
export class UserInteractionsRequest extends Message<UserInteractionsRequest> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  constructor(data?: PartialMessage<UserInteractionsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.UserInteractionsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserInteractionsRequest {
    return new UserInteractionsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserInteractionsRequest {
    return new UserInteractionsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserInteractionsRequest {
    return new UserInteractionsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UserInteractionsRequest | PlainMessage<UserInteractionsRequest> | undefined, b: UserInteractionsRequest | PlainMessage<UserInteractionsRequest> | undefined): boolean {
    return proto3.util.equals(UserInteractionsRequest, a, b);
  }
}

/**
 * @generated from message users.UserInteractionsReply
 */
export class UserInteractionsReply extends Message<UserInteractionsReply> {
  /**
   * @generated from field: repeated users.InteractionReply interactions = 1;
   */
  interactions: InteractionReply[] = [];

  constructor(data?: PartialMessage<UserInteractionsReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.UserInteractionsReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "interactions", kind: "message", T: InteractionReply, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserInteractionsReply {
    return new UserInteractionsReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserInteractionsReply {
    return new UserInteractionsReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserInteractionsReply {
    return new UserInteractionsReply().fromJsonString(jsonString, options);
  }

  static equals(a: UserInteractionsReply | PlainMessage<UserInteractionsReply> | undefined, b: UserInteractionsReply | PlainMessage<UserInteractionsReply> | undefined): boolean {
    return proto3.util.equals(UserInteractionsReply, a, b);
  }
}

/**
 * @generated from message users.InteractionReply
 */
export class InteractionReply extends Message<InteractionReply> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string user_id = 2;
   */
  userId = "";

  /**
   * @generated from field: string isrc = 3;
   */
  isrc = "";

  /**
   * @generated from field: string decision = 4;
   */
  decision = "";

  /**
   * @generated from field: int64 deezer_track_id = 5;
   */
  deezerTrackId = protoInt64.zero;

  /**
   * @generated from field: string source = 6;
   */
  source = "";

  /**
   * @generated from field: string artist = 7;
   */
  artist = "";

  /**
   * @generated from field: string title = 8;
   */
  title = "";

  constructor(data?: PartialMessage<InteractionReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.InteractionReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "isrc", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "decision", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "deezer_track_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "artist", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InteractionReply {
    return new InteractionReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InteractionReply {
    return new InteractionReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InteractionReply {
    return new InteractionReply().fromJsonString(jsonString, options);
  }

  static equals(a: InteractionReply | PlainMessage<InteractionReply> | undefined, b: InteractionReply | PlainMessage<InteractionReply> | undefined): boolean {
    return proto3.util.equals(InteractionReply, a, b);
  }
}

/**
 * @generated from message users.CreatePlaylistRequest
 */
export class CreatePlaylistRequest extends Message<CreatePlaylistRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  constructor(data?: PartialMessage<CreatePlaylistRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.CreatePlaylistRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreatePlaylistRequest {
    return new CreatePlaylistRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreatePlaylistRequest {
    return new CreatePlaylistRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreatePlaylistRequest {
    return new CreatePlaylistRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreatePlaylistRequest | PlainMessage<CreatePlaylistRequest> | undefined, b: CreatePlaylistRequest | PlainMessage<CreatePlaylistRequest> | undefined): boolean {
    return proto3.util.equals(CreatePlaylistRequest, a, b);
  }
}

/**
 * @generated from message users.PlaylistReply
 */
export class PlaylistReply extends Message<PlaylistReply> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: int32 track_count = 3;
   */
  trackCount = 0;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<PlaylistReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.PlaylistReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "track_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "created_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlaylistReply {
    return new PlaylistReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlaylistReply {
    return new PlaylistReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlaylistReply {
    return new PlaylistReply().fromJsonString(jsonString, options);
  }

  static equals(a: PlaylistReply | PlainMessage<PlaylistReply> | undefined, b: PlaylistReply | PlainMessage<PlaylistReply> | undefined): boolean {
    return proto3.util.equals(PlaylistReply, a, b);
  }
}

/**
 * @generated from message users.PlaylistsListReply
 */
export class PlaylistsListReply extends Message<PlaylistsListReply> {
  /**
   * @generated from field: repeated users.PlaylistReply playlists = 1;
   */
  playlists: PlaylistReply[] = [];

  constructor(data?: PartialMessage<PlaylistsListReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.PlaylistsListReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "playlists", kind: "message", T: PlaylistReply, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlaylistsListReply {
    return new PlaylistsListReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlaylistsListReply {
    return new PlaylistsListReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlaylistsListReply {
    return new PlaylistsListReply().fromJsonString(jsonString, options);
  }

  static equals(a: PlaylistsListReply | PlainMessage<PlaylistsListReply> | undefined, b: PlaylistsListReply | PlainMessage<PlaylistsListReply> | undefined): boolean {
    return proto3.util.equals(PlaylistsListReply, a, b);
  }
}

/**
 * @generated from message users.DeletePlaylistRequest
 */
export class DeletePlaylistRequest extends Message<DeletePlaylistRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  constructor(data?: PartialMessage<DeletePlaylistRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.DeletePlaylistRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeletePlaylistRequest {
    return new DeletePlaylistRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeletePlaylistRequest {
    return new DeletePlaylistRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeletePlaylistRequest {
    return new DeletePlaylistRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeletePlaylistRequest | PlainMessage<DeletePlaylistRequest> | undefined, b: DeletePlaylistRequest | PlainMessage<DeletePlaylistRequest> | undefined): boolean {
    return proto3.util.equals(DeletePlaylistRequest, a, b);
  }
}

/**
 * @generated from message users.PlaylistTrack
 */
export class PlaylistTrack extends Message<PlaylistTrack> {
  /**
   * @generated from field: int64 deezer_track_id = 1;
   */
  deezerTrackId = protoInt64.zero;

  /**
   * @generated from field: string title = 2;
   */
  title = "";

  /**
   * @generated from field: string isrc = 3;
   */
  isrc = "";

  /**
   * @generated from field: int64 artist_id = 4;
   */
  artistId = protoInt64.zero;

  /**
   * @generated from field: string artist_name = 5;
   */
  artistName = "";

  /**
   * @generated from field: string album_cover = 6;
   */
  albumCover = "";

  /**
   * @generated from field: google.protobuf.Timestamp added_at = 7;
   */
  addedAt?: Timestamp;

  constructor(data?: PartialMessage<PlaylistTrack>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.PlaylistTrack";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deezer_track_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "isrc", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "artist_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "artist_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "album_cover", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "added_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlaylistTrack {
    return new PlaylistTrack().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlaylistTrack {
    return new PlaylistTrack().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlaylistTrack {
    return new PlaylistTrack().fromJsonString(jsonString, options);
  }

  static equals(a: PlaylistTrack | PlainMessage<PlaylistTrack> | undefined, b: PlaylistTrack | PlainMessage<PlaylistTrack> | undefined): boolean {
    return proto3.util.equals(PlaylistTrack, a, b);
  }
}

/**
 * @generated from message users.AddTrackToPlaylistRequest
 */
export class AddTrackToPlaylistRequest extends Message<AddTrackToPlaylistRequest> {
  /**
   * @generated from field: string playlist_id = 1;
   */
  playlistId = "";

  /**
   * @generated from field: int64 deezer_track_id = 2;
   */
  deezerTrackId = protoInt64.zero;

  /**
   * @generated from field: string title = 3;
   */
  title = "";

  /**
   * @generated from field: string isrc = 4;
   */
  isrc = "";

  /**
   * @generated from field: int64 artist_id = 5;
   */
  artistId = protoInt64.zero;

  /**
   * @generated from field: string artist_name = 6;
   */
  artistName = "";

  /**
   * @generated from field: string album_cover = 7;
   */
  albumCover = "";

  constructor(data?: PartialMessage<AddTrackToPlaylistRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.AddTrackToPlaylistRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "playlist_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "deezer_track_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "isrc", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "artist_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "artist_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "album_cover", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddTrackToPlaylistRequest {
    return new AddTrackToPlaylistRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddTrackToPlaylistRequest {
    return new AddTrackToPlaylistRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddTrackToPlaylistRequest {
    return new AddTrackToPlaylistRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AddTrackToPlaylistRequest | PlainMessage<AddTrackToPlaylistRequest> | undefined, b: AddTrackToPlaylistRequest | PlainMessage<AddTrackToPlaylistRequest> | undefined): boolean {
    return proto3.util.equals(AddTrackToPlaylistRequest, a, b);
  }
}

/**
 * @generated from message users.PlaylistTrackReply
 */
export class PlaylistTrackReply extends Message<PlaylistTrackReply> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * @generated from field: users.PlaylistTrack track = 2;
   */
  track?: PlaylistTrack;

  constructor(data?: PartialMessage<PlaylistTrackReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.PlaylistTrackReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "track", kind: "message", T: PlaylistTrack },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlaylistTrackReply {
    return new PlaylistTrackReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlaylistTrackReply {
    return new PlaylistTrackReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlaylistTrackReply {
    return new PlaylistTrackReply().fromJsonString(jsonString, options);
  }

  static equals(a: PlaylistTrackReply | PlainMessage<PlaylistTrackReply> | undefined, b: PlaylistTrackReply | PlainMessage<PlaylistTrackReply> | undefined): boolean {
    return proto3.util.equals(PlaylistTrackReply, a, b);
  }
}

/**
 * @generated from message users.RemoveTrackFromPlaylistRequest
 */
export class RemoveTrackFromPlaylistRequest extends Message<RemoveTrackFromPlaylistRequest> {
  /**
   * @generated from field: string playlist_id = 1;
   */
  playlistId = "";

  /**
   * @generated from field: int64 deezer_track_id = 2;
   */
  deezerTrackId = protoInt64.zero;

  constructor(data?: PartialMessage<RemoveTrackFromPlaylistRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.RemoveTrackFromPlaylistRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "playlist_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "deezer_track_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveTrackFromPlaylistRequest {
    return new RemoveTrackFromPlaylistRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveTrackFromPlaylistRequest {
    return new RemoveTrackFromPlaylistRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveTrackFromPlaylistRequest {
    return new RemoveTrackFromPlaylistRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RemoveTrackFromPlaylistRequest | PlainMessage<RemoveTrackFromPlaylistRequest> | undefined, b: RemoveTrackFromPlaylistRequest | PlainMessage<RemoveTrackFromPlaylistRequest> | undefined): boolean {
    return proto3.util.equals(RemoveTrackFromPlaylistRequest, a, b);
  }
}

/**
 * @generated from message users.GetPlaylistTracksRequest
 */
export class GetPlaylistTracksRequest extends Message<GetPlaylistTracksRequest> {
  /**
   * @generated from field: string playlist_id = 1;
   */
  playlistId = "";

  constructor(data?: PartialMessage<GetPlaylistTracksRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.GetPlaylistTracksRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "playlist_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPlaylistTracksRequest {
    return new GetPlaylistTracksRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPlaylistTracksRequest {
    return new GetPlaylistTracksRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPlaylistTracksRequest {
    return new GetPlaylistTracksRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetPlaylistTracksRequest | PlainMessage<GetPlaylistTracksRequest> | undefined, b: GetPlaylistTracksRequest | PlainMessage<GetPlaylistTracksRequest> | undefined): boolean {
    return proto3.util.equals(GetPlaylistTracksRequest, a, b);
  }
}

/**
 * @generated from message users.PlaylistTracksListReply
 */
export class PlaylistTracksListReply extends Message<PlaylistTracksListReply> {
  /**
   * @generated from field: repeated users.PlaylistTrack tracks = 1;
   */
  tracks: PlaylistTrack[] = [];

  constructor(data?: PartialMessage<PlaylistTracksListReply>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "users.PlaylistTracksListReply";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "tracks", kind: "message", T: PlaylistTrack, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlaylistTracksListReply {
    return new PlaylistTracksListReply().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlaylistTracksListReply {
    return new PlaylistTracksListReply().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlaylistTracksListReply {
    return new PlaylistTracksListReply().fromJsonString(jsonString, options);
  }

  static equals(a: PlaylistTracksListReply | PlainMessage<PlaylistTracksListReply> | undefined, b: PlaylistTracksListReply | PlainMessage<PlaylistTracksListReply> | undefined): boolean {
    return proto3.util.equals(PlaylistTracksListReply, a, b);
  }
}

