// @generated by protoc-gen-connect-web v0.8.6 with parameter "target=ts,import_extension=none"
// @generated from file users.proto (package users, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateUserRequest, DeleteReply, Empty, LoginReply, LoginRequest, LogoutReply, LogoutRequest, RefreshReply, RefreshRequest, UpdateUserRequest, UserReply, UserRequest, UsersReply } from "./users_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service users.UserService
 */
export const UserService = {
  typeName: "users.UserService",
  methods: {
    /**
     * @generated from rpc users.UserService.Refresh
     */
    refresh: {
      name: "Refresh",
      I: RefreshRequest,
      O: RefreshReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.Logout
     */
    logout: {
      name: "Logout",
      I: LogoutRequest,
      O: LogoutReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: UserReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserRequest,
      O: UserReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.DeleteUser
     */
    deleteUser: {
      name: "DeleteUser",
      I: UserRequest,
      O: DeleteReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: UserRequest,
      O: UserReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.GetUsers
     */
    getUsers: {
      name: "GetUsers",
      I: Empty,
      O: UsersReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginReply,
      kind: MethodKind.Unary,
    },
  }
} as const;

