// @generated by protoc-gen-connect-web v0.8.6 with parameter "target=ts,import_extension=none"
// @generated from file users.proto (package users, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddTrackToPlaylistRequest, CreatePlaylistRequest, CreateUserRequest, DeleteAllPlaylistsRequest, DeletePlaylistRequest, DeleteReply, Empty, ExportPlaylistReply, ExportPlaylistRequest, GetPlaylistTracksRequest, LoginReply, LoginRequest, LogoutReply, LogoutRequest, PlaylistReply, PlaylistsListReply, PlaylistTrackReply, PlaylistTracksListReply, RefreshReply, RefreshRequest, RemoveTrackFromPlaylistRequest, ResetSwipeHistoryRequest, SpotifyAuthUrlReply, SpotifyCallbackReply, SpotifyCallbackRequest, UpdateUserRequest, UserInteractionsReply, UserInteractionsRequest, UserReply, UserRequest, UsersReply, UserStatsReply, UserStatsRequest } from "./users_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service users.UserService
 */
export const UserService = {
  typeName: "users.UserService",
  methods: {
    /**
     * @generated from rpc users.UserService.Refresh
     */
    refresh: {
      name: "Refresh",
      I: RefreshRequest,
      O: RefreshReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.Logout
     */
    logout: {
      name: "Logout",
      I: LogoutRequest,
      O: LogoutReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: UserReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserRequest,
      O: UserReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.DeleteUser
     */
    deleteUser: {
      name: "DeleteUser",
      I: UserRequest,
      O: DeleteReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: UserRequest,
      O: UserReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.GetUsers
     */
    getUsers: {
      name: "GetUsers",
      I: Empty,
      O: UsersReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.GetUserInteractions
     */
    getUserInteractions: {
      name: "GetUserInteractions",
      I: UserInteractionsRequest,
      O: UserInteractionsReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.CreatePlaylist
     */
    createPlaylist: {
      name: "CreatePlaylist",
      I: CreatePlaylistRequest,
      O: PlaylistReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.GetMyPlaylists
     */
    getMyPlaylists: {
      name: "GetMyPlaylists",
      I: Empty,
      O: PlaylistsListReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.DeletePlaylist
     */
    deletePlaylist: {
      name: "DeletePlaylist",
      I: DeletePlaylistRequest,
      O: DeleteReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.AddTrackToPlaylist
     */
    addTrackToPlaylist: {
      name: "AddTrackToPlaylist",
      I: AddTrackToPlaylistRequest,
      O: PlaylistTrackReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.RemoveTrackFromPlaylist
     */
    removeTrackFromPlaylist: {
      name: "RemoveTrackFromPlaylist",
      I: RemoveTrackFromPlaylistRequest,
      O: DeleteReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.GetPlaylistTracks
     */
    getPlaylistTracks: {
      name: "GetPlaylistTracks",
      I: GetPlaylistTracksRequest,
      O: PlaylistTracksListReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.GetUserStats
     */
    getUserStats: {
      name: "GetUserStats",
      I: UserStatsRequest,
      O: UserStatsReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.GetSpotifyAuthUrl
     */
    getSpotifyAuthUrl: {
      name: "GetSpotifyAuthUrl",
      I: Empty,
      O: SpotifyAuthUrlReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.HandleSpotifyCallback
     */
    handleSpotifyCallback: {
      name: "HandleSpotifyCallback",
      I: SpotifyCallbackRequest,
      O: SpotifyCallbackReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.ExportPlaylist
     */
    exportPlaylist: {
      name: "ExportPlaylist",
      I: ExportPlaylistRequest,
      O: ExportPlaylistReply,
      kind: MethodKind.Unary,
    },
    /**
     * Danger Zone
     *
     * @generated from rpc users.UserService.ResetSwipeHistory
     */
    resetSwipeHistory: {
      name: "ResetSwipeHistory",
      I: ResetSwipeHistoryRequest,
      O: DeleteReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.DeleteAllPlaylists
     */
    deleteAllPlaylists: {
      name: "DeleteAllPlaylists",
      I: DeleteAllPlaylistsRequest,
      O: DeleteReply,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UserService.DeleteAccount
     */
    deleteAccount: {
      name: "DeleteAccount",
      I: Empty,
      O: DeleteReply,
      kind: MethodKind.Unary,
    },
  }
} as const;

